turtlebot3_waffle_sim:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # Position Controllers ---------------------------------------
  left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_left_joint
    pid: {p: 1.0, i: 0.001, d: 0.01}
  right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_right_joint
    pid: {p: 1.0, i: 0.001, d: 0.01}
  suspension_one:
    type: effort_controllers/JointPositionController
    joint: left_caster_joint
    pid: {p: 100, i: 0.0000, d: 30}
  suspension_two:
    type: effort_controllers/JointPositionController
    joint: right_caster_joint
    pid: {p: 100, i: 0.0000, d: 30}
  suspension_three:
    type: effort_controllers/JointPositionController
    joint: left_suspension_joint
    pid: {p: 100, i: 0.0000, d: 30}
  suspension_four:
    type: effort_controllers/JointPositionController
    joint: right_suspension_joint
    pid: {p: 100, i: 0.0000, d: 30}
