model20:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # Position Controllers ---------------------------------------
  left_front_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_front_wheel_joint
    pid: {p: 1.0, i: 0.001, d: 0.0105}
  right_front_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_front_wheel_joint
    pid: {p: 1.0, i: 0.001, d: 0.0105}
  left_rear_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_rear_wheel_joint
    pid: {p: 1.0, i: 0.001, d: 0.0105}
  right_rear_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_rear_wheel_joint
    pid: {p: 1.0, i: 0.001, d: 0.0105}
  left_front_wheel_suspension_controller:
    type: effort_controllers/JointPositionController
    joint: left_front_wheel_suspension_joint
    pid: {p: 100, i: 0.0000, d: 30}
  left_rear_wheel_suspension_controller:
    type: effort_controllers/JointPositionController
    joint: left_rear_wheel_suspension_joint
    pid: {p: 100, i: 0.0000, d: 30}
  right_front_wheel_suspension_controller:
    type: effort_controllers/JointPositionController
    joint: right_front_wheel_suspension_joint
    pid: {p: 100, i: 0.0000, d: 30}
  right_rear_wheel_suspension_controller:
    type: effort_controllers/JointPositionController
    joint: right_rear_wheel_suspension_joint
    pid: {p: 100, i: 0.0000, d: 30}
